[project]

requires-python=">=3.9"

[tool.ruff]

line-length = 79
src = ['src']

#rooles
select = [
  "E", # pycodestyle
  "F", # pyflakes
  "UP", # pyugrade 
  "N", # pep8 examination
  "ERA001" # found commented-out code
]
